#!/bin/sh
###
# Installation of NeoVim configuration
#
# @author Manne Busk
###
RED="\e[31m"
GREEN="\e[32m"
NORMAL="\e[39m"
CYAN="\e[95m"
DIR="$( cd "$( dirname "$0" )" && pwd )"
PLUG=~/.local/share/nvim/site/autoload/plug.vim 
if [ -f $PLUG ]; then
    echo -e $CYAN"Plugin manager already installed at "$NORMAL"~/.local/share/nvim/site/autoload/plug.vim"
else
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    echo -e $GREEN"Plugin manager installed into "$NORMAL"~/.local/share/nvim/site/autoload/plug.vim"
fi

INIT=~/.config/nvim/init.vim
if [ -f $INIT ]; then
    echo -e $CYAN"NeoVim configuration already exists in "$NORMAL"~/.config/nvim/init.vim"
    echo -e $RED"FAILED"$NORMAL
    echo -e $CYAN"Please remove existing configuration and run this script again."$NORMAL
else
    mkdir -p ~/.config/nvim
    ln -s $DIR/init.vim ~/.config/nvim/init.vim
    echo -e $GREEN"NeoVim configuraion linked into "$NORMAL"~/.config/nvim/init.vim"
    echo -e $GREEN"Complete!"$NORMAL
fi

INIT_SNIPPETS=~/.config/nvim/snippets/vim.snippets
if [ -f $INIT_SNIPPETS ]; then
    echo -e $CYAN"Snippets already linked to "$NORMAL"~/.config/nvim/snippets/"
    echo -e $RED"FAILED"$NORMAL
else
    ln -s $DIR/snippets ~/.config/nvim/snippets
    echo -e $GREEN"Snippets linked into "$NORMAL"~/.config/nvim/snippets/"
    echo -e $GREEN"Complete!"$NORMAL
fi
